### ISSUE TITLE
Suggestion: show AS name when hovering over connectivity graphic

### ISSUE THREAD

**Issue by n-st** [bgptools/issues#1]
On the connectivity overview graphic (e.g. [here](https://bgp.tools/as/112#connectivity)), the user can long-tap or hover their mouse over an AS number to see its `title` attribute.
Currently, that attribute only contains the same information (AS number) already shown in the graphic. It would be useful to get the AS name (like in the Upstream/Peer list below the graphic), especially for ASNs that aren't well-known.

**Comment by benjojo** [comment]
This has been added now
