### ISSUE TITLE
More flexible search would be nice

### ISSUE THREAD

**Issue by RobinGeuze** [bgptools/issues#10]
Currently only a directly announced prefix will be found. For example if I search for 149.210.210.0/24 it will give me a 404. It would be nice if a subrange or even a specific ip would return the most specific announcement that it is in.

A secondary nice to have might be a text search for the AS name or netname and such, but that will be more work probably.

I've heard from reliable sources this is written in Go, if you guys like I could type some stuff in myself.

**Comment by bitcynth** [comment]
> It would be nice if a subrange or even a specific ip would return the most specific announcement that it is in.

afaik this is already the case for specific IPs but if you specify the subnet length, then it won't. (I think this is intentional)

**Comment by RobinGeuze** [comment]
Oh apparently you can search for arbitrary text, the subtext for the search field just doesn't mention it. I guess I should look a little further next time.
