### ISSUE TITLE
Thoughts on separating AS Cone by IP version

### ISSUE THREAD

**Issue by asdfjkluiop** [bgptools/issues#100]
I might be the only person that finds this useful but what are your thoughts on separating the AS Cone stat by IP version? Currently I believe it's total combined cone which is still a useful statistic but there are plenty of ASes that don't have the same v4 and v6 uplinks as well as plenty of networks that are single stacked. Additionally I think it might be a good idea to not limit the stat page to a 960px width but rather allow it to be a certain percentage of the total view area.

**Comment by benjojo** [comment]
This would be reasonably heavy RAM+Compute to add (as Cone is calculated in real time), and I'm not sure if there is much benefit in doing so as the one major difference between the v6-internet and v4-internet is HE.

Single stacked networks are interesting (well, more like dual stack networks are interesting, given there are less of them). But I think adding this to the cone feature is a little too deep in the weeds for 99.5% of users.
