### ISSUE TITLE
Show Overlap IXP/Facilities button

### ISSUE THREAD

**Issue by benjojo** [bgptools/issues#101]
It would be nice for me (and other customers) to have a button on the IXP tab that only shows IXPs that both *I* have, and the network I'm looking at has.

Ideally also we can pull in PeeringDB facility info too and show overlap

**Comment by forkwhilefork** [comment]
That would be nice. Right now I use PeeringManager for this, and I have to add the peer ASN in order to see that data even if I end up not peering.

**Comment by benjojo** [comment]
![image](https://github.com/bgptools/issues/assets/1504626/ae0a6d5c-58df-4588-9d48-c28a24b080f7)
