### ISSUE TITLE
Feature request: Show Peers, Upstreams, Downstreams above Network Policy in Connectivity tab

### ISSUE THREAD

**Issue by JeeveStobs** [bgptools/issues#107]
URL:
```
https://bgp.tools/as/1#connectivity
```

Browser (User-Agent if you can): 
```
Any
```

Error base64 blob (If a site error):
```
N/A
```

What were you expecting:
```
Show Peers, Upstreams, Downstreams above Network Policy in the Connectivity tab
```

What happened:
```
Network Policy is above Peers, Upstreams, Downstreams in the Connectivity tab
```

**Comment by benjojo** [comment]
Network policy is a key feature of the Connectivity tab, You can use the links highlighted in red to "jump" to the Peers, Upstreams, Downstreams section in a pinch

![image](https://github.com/bgptools/issues/assets/1504626/0fb1d4ef-7fdb-4baa-a884-759de4fa7442)

**Comment by JeeveStobs** [comment]
No doubt network policy is a key feature of the Connectivity tab – however the links highlighted above aren't present when viewing a netblock, example: https://bgp.tools/prefix/103.144.176.0/24#connectivity

The links _do_ appear when viewing the Connectivity tab at the AS level.
