### ISSUE TITLE
Name Attached on BGP Propagation

### ISSUE THREAD

**Issue by rapdodge** [bgptools/issues#110]
(Example) URL:
```
https://bgp.tools/prefix/123.253.233.0/24#connectivity
```

Browser (User-Agent if you can): 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61
```

Error base64 blob (If a site error):
```
Non applicable
```

What were you expecting:
```
The name on the ASN does not include "PT"
```

What happened:
```
For your information,
On average, the name of an ISP in Indonesia in their ASN has "PT" in front of it, so the name will only be "PT" in BGP Propagation

Is it possible to have a word filter to remove "PT"?

And I think it would be better for Indonesian ASNs is having 2 words.

Example

- AS17670 PT. MNC Kabel Mediacom -> MNC Kabel
- AS137366 PT iForte Solusi Infotek -> iForte Solusi
- AS24203 PT XL Axiata -> XL Axiata
- AS9341	PT INDONESIA COMNETS PLUS -> INDONESIA COMNETS

```
![image](https://github.com/bgptools/issues/assets/33513626/d2e6adf1-3829-4898-b0f8-32e4d142c923)

**Comment by benjojo** [comment]
I've built in some hints to try and prevent this. So for now:

```
- AS17670 PT. MNC Kabel Mediacom -> MNC
- AS137366 PT iForte Solusi Infotek -> iForte
- AS24203 PT XL Axiata -> XL
- AS9341	PT INDONESIA COMNETS PLUS -> COMNETS
```

It's not perfect, but I plan to add a "short name" override on the edit page, since this is already being done for DTAG, Sparkle etc

**Comment by rapdodge** [comment]
> I've built in some hints to try and prevent this. So for now:
> 
> ```
> - AS17670 PT. MNC Kabel Mediacom -> MNC
> - AS137366 PT iForte Solusi Infotek -> iForte
> - AS24203 PT XL Axiata -> XL
> - AS9341	PT INDONESIA COMNETS PLUS -> COMNETS
> ```
> 
> It's not perfect, but I plan to add a "short name" override on the edit page, since this is already being done for DTAG, Sparkle etc

Great, if shortname override on edit page are available, I will be loved to adding the shortnames of most ISPs in Indonesia
