### ISSUE TITLE
OCD feature request: uppercase AS set names

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#112]
URL:
```
https://bgp.tools/as-set/RIPE::as51019:as-routing-in-iceland
```

Browser (User-Agent if you can): 
```
n/a
```

Error base64 blob (If a site error):
```
n/a
```

What were you expecting:
```
AS set name should be formatted in uppercase, as is most commonly done.
```

What happened:
```
AS set name follows case of whatever is in the URI.
```

How to fix:
```
<p id="network-name" class="heading-xlarge">as51019:as-routing-in-ice...</p>
```
becomes
```
<p id="network-name" class="heading-xlarge" style="text-transform: uppercase;">as51019:as-routing-in-ice...</p>
```

Thanks, on behalf of the region of my brain that handles pettiness.

**Comment by elinarbur** [comment]
Ah, maybe apply the uppercase transform to the `<strong>` tag in `Full Name <strong>as51019:as-routing-in-iceland</strong></p>` too.

**Comment by benjojo** [comment]
Sure this makes sense I think it was done originally to make sure that the
titles had the same cardinality, but I agree with you and in that it makes
sense for this to be uppercase
