### ISSUE TITLE
Add link to website in slack messages

### ISSUE THREAD

**Issue by davidc** [bgptools/issues#118]
It would be good if the Slack messages embedded a hyperlink to the alert page on the bgp.tools website, where more information about the issue is available.

**Comment by benjojo** [comment]
![image](https://github.com/bgptools/issues/assets/1504626/e022cb8f-84b5-4aae-8e4c-6c2122aa5efb)

All Slack alert messages now contain buttons to the alert, and to all alerts!

**Comment by davidc** [comment]
Thanks for adding this feature!

1) The "has been detected as a new upstream" alerts have an embedded hyperlink in the text that's no longer necessary.

2) The "has been detected as a new upstream" alerts have a little slack warning triangle, not sure why, see screenshot. The "has been lost as an upstream" alerts don't have this.

![image](https://github.com/bgptools/issues/assets/1050152/ab33e200-8e8c-4743-bc0e-e6ebc43aabf1)

**Comment by benjojo** [comment]
Yeah I need to think about what to do with the link (it's a slightly non obvious quirk to fix), The warning triangle is some other quirk (because the buttons are suppose to be a wider interactivity feature for slack that I am (ab)using)
