### ISSUE TITLE
Incorrect Values in "Understanding TCP MSS Values" Table

### ISSUE THREAD

**Issue by billchenchina** [bgptools/issues#122]
The table "Common TCP MSS Values" in the article "Understanding TCP MSS Values" on the website contains incorrect values for "Min IPv6 MTU" and "Min IPv6 MTU with TCP Timestamps".

## URL

https://bgp.tools/kb/understanding-tcp-mss

## What were you expecting

The values for "Min IPv6 MTU" and "Min IPv6 MTU with TCP Timestamps" should be calculated correctly as follows:

| Use Case | IPv6 MSS Value |
| - | - |
| ... | ... |
| Min IPv6 MTU | 1280 - 40 - 20 = 1220 |
| Min IPv6 MTU with TCP Timestamps | 1280 - 40 - 32 = 1208 |

## What happened

The table currently displays the following incorrect values:

| Use Case | IPv6 MSS Value |
| - | - |
| ... | ... |
| Min IPv6 MTU | 1240 |
| Min IPv6 MTU with TCP Timestamps | 1228 |

## Some boring text generated by ChatGPT

<details><summary>Details</summary>

The Maximum Segment Size (MSS) is the maximum amount of data that can be sent in a single TCP segment. In IPv6, the minimum Maximum Transmission Unit (MTU) is 1280 bytes. The MTU represents the maximum size of a packet that can be transmitted over a network.

When TCP Timestamps are not used, the MSS value for IPv6 is typically calculated as the MTU minus the IPv6 header size (40 bytes) and the TCP header size (20 bytes). Therefore, the MSS value for IPv6 without TCP Timestamps would be:

MSS = MTU - IPv6 header size - TCP header size
= 1280 - 40 - 20
= 1220 bytes

When TCP Timestamps are used, an additional 12 bytes are added to the TCP header. Therefore, the MSS value for IPv6 with TCP Timestamps would be:

MSS = MTU - IPv6 header size - TCP header size - TCP Timestamps size
= 1280 - 40 - 20 - 12
= 1208 bytes

It's worth noting that the MSS value can be further reduced if additional headers or options are present in the IPv6 or TCP headers.
</details>

**Comment by benjojo** [comment]
I agree on the with timestamps value, but from testing the real world Linux Min v6 MTU value is 1220:

```
root@test-debian11:~# ip l | grep 1280
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000

root@test-debian11:~# ip l | grep 1280
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000

root@test-debian11:~# ncat -6 bgp.tools 43 &
[4] 1217

root@test-debian11:~# ss -iplant 
State                       Recv-Q                   Send-Q                                                              Local Address:Port                                                   Peer Address:Port                   Process                                                                                                                                                                                                                           
...
ESTAB                       0                        0                                          [xxx]:33528                                     [2a0c:2f07:9459:443::247]:43                      users:(("ncat",pid=1217,fd=3))
	 cubic wscale:7,7 rto:204 rtt:3.591/1.795 mss:1220 pmtu:1280 rcvmss:536 advmss:1220 cwnd:10 bytes_acked:1 segs_out:2 segs_in:1 send 27179059bps lastsnd:1732 lastrcv:1732 lastack:1732 pacing_rate 54358112bps delivered:1 rcv_space:12200 rcv_ssthresh:64316 minrtt:3.591
```

KB corrected, this issue will auto close when that update is out
