### ISSUE TITLE
Hijack alert doesn't seem to respect RADB IRR

### ISSUE THREAD

**Issue by athompson-merlin** [bgptools/issues#125]
URL:
```
https://bgp.tools/authed/manage-alerts?detail=6af8a996-3253-41c0-bea3-d37ff94e729f
and
```

What were you expecting:
```
No alert.
```

What happened:
```
An alert.
```

According to [https://bgp.tools/kb/alert-help-hijack], the alert should be suppressed if there's a valid IRR record supporting the current advertising AS.  An "authenticated" IRR entry is merely defined as one done through the IRR portal. 

I have two valid entries in RADB for this network, because it can be originated by either AS - both are correct (shown below):
![image](https://github.com/bgptools/issues/assets/56890769/bb2dfdd3-f439-4466-a491-67471a1ec900)

What am I missing?  Why isn't this alert being suppressed?

**Comment by benjojo** [comment]
RADB is not authenticated, authenticated means RIPE/ARIN/APNIC/LACNIC/AFRINIC, as their IRR databases do not allow you to insert entries for IP prefixes that you do not have administrative control over

Not a bug, but I will update the documentation
