### ISSUE TITLE
Suggestion: Tag list export

### ISSUE THREAD

**Issue by molangning** [bgptools/issues#127]
If there is a way to export tags such as tor and vpn it would be really helpful for robots.

Alternatively, if there is a way to export the entire db of asn to tags mapping that would be great.

**Comment by benjojo** [comment]
From: https://bgp.tools/kb/api

> Tag export
> Tags can be exported by putting a .csv or .txt on the end of the URL for a tag list. For example: https://bgp.tools/tags/cdn.csv

**Comment by molangning** [comment]
@benjojo That's not what I meant, I meant that I need a lists of tags that bgp.tools have for the asns. Sorry for the misunderstanding.
