### ISSUE TITLE
Addition suggestion: show pending edits

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#133]
What I'm suggesting is pretty simple: what if pending edits for an ASN showed up on the edit page for that ASN?

I don't know often it happens that an ASN is edited twice in a short period of time but having this indicator to users who submit edits might help cut down on duplicate edits. It could also assist users such as myself that edit large sets of ASNs ,to clarify which networks have already been edited and which haven't.
For example I revisit the Iceland dataset regularly to update websites, company names, spelling of company names, and relevant tags.

Not sure if the time required for a feature of this sort would make sense, won't claim to know the perfect implementation of such a feature. Nevertheless I throw my idea in the idea pool <3

**Comment by benjojo** [comment]
The issue is that people will almost certainly put offensive content in the
edits (they already do) and I prefer that I am the only one who has to see
that kind of stuff
