### ISSUE TITLE
BGP session

### ISSUE THREAD

**Issue by pcela** [bgptools/issues#137]
Hi.
I cannot add a new BGP session. The message below appears:

```
Failed to add bgp session

Reason: To preserve capacity, we are limiting how many sesions can be made from some types of ASNs. The current count of such sessions is 351 while the target is 250 sessions

Do not press back. The token used to protect the form has been invalidated. [Click here to try again](https://bgp.tools/authed/manage-peering?new=1)
```
Currently, I do not have any session configured.

**Comment by benjojo** [comment]
It is a global limit, not a bug

**Comment by baragoon** [comment]
does this limitation also apply to paid subscriptions?

**Comment by pcela** [comment]
Probably not. For me, the limit is 0 sessions, and there are those who have several (on personal ASN).
