### ISSUE TITLE
There seems to be a problem with the DNS detection function

### ISSUE THREAD

**Issue by 9bingyin** [bgptools/issues#138]
Browser (User-Agent if you can): 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
```
The DNS detection feature of BGP.Tools seems to be inaccurate, I have used several websites to detect this, and it seems that the DNS of other users is included in the results returned by BGP.Tools, and from the json returned, it also contains the ECS information of other users, which may cause some privacy issues.

- https://surfshark.com/dns-leak-test
![surfshark.com](https://github.com/bgptools/issues/assets/37502927/bcfd61f7-ac31-41f6-847d-3b545636ee35)
- https://www.dnsleaktest.com/
![www.dnsleaktest.com](https://github.com/bgptools/issues/assets/37502927/d68b3e69-1e9e-402c-b17e-5f85db8a55c6)
- https://browserleaks.com/dns
![browserleaks.com](https://github.com/bgptools/issues/assets/37502927/9e49b473-1099-4b17-aa98-be7f792991cf)
- https://bgp.tools/
![bgp.tools](https://github.com/bgptools/issues/assets/37502927/84e41d28-1c10-41f2-8406-cc11576b51be)

**Comment by benjojo** [comment]
The way this feature works would make that quite hard to do. However one of the things that the bgp.tools DNS test does do that most others don't is it adds a false delay to try and trigger retry behaviour, so you may find that those extra DNS servers are actually fallback configured.

Without a way to reproduce your findings, I cannot really give any extra information, but I am reasonably confident that those are correct results
