### ISSUE TITLE
Question: Why are AS numbers displayed in roman numerals?

### ISSUE THREAD

**Issue by klipspringr** [bgptools/issues#140]
Curious!

https://bgp.tools/as/15169

![image](https://github.com/bgptools/issues/assets/97002039/44838a05-76a6-4386-9875-904a0f8c641e)

**Comment by baragoon** [comment]
Was this an April Fool's joke?

**Comment by benjojo** [comment]
Yes

**Comment by klipspringr** [comment]
Very good!
