### ISSUE TITLE
Ericsson & Proxmox OUI icons

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#143]
This issue is rather simple, I think it would be nice to give the same treatment to Ericsson and Proxmox OUIs similar to Nokia and VMWare in displaying an icon next to members using these two on an IX.

Currently they look like this:
![image](https://github.com/bgptools/issues/assets/47786934/c1bd1d4f-60bd-41c9-a8ed-2df31ab33dab)
![image](https://github.com/bgptools/issues/assets/47786934/d704a8cd-9025-4679-a328-db886493df72)

Hopefully you agree :)

**Comment by benjojo** [comment]
Done
