### ISSUE TITLE
Connectivity graph miss my sessions when logged in with non-root user

### ISSUE THREAD

**Issue by sorah** [bgptools/issues#144]
URL: https://bgp.tools/as/13335#connectivity

Browser (User-Agent if you can): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

----

What were you expecting:

Connectivity graph includes my AS sessions

What happened:

- when I signed in with AS59128 organization root account, my AS59128 BGP sessions appear in connectivity graphs (as expected)
- when I signed in with admin accounts belong to the AS59128 organization, those sessions miss in connectivity graphs

**Comment by benjojo** [comment]
Are the sessions flagged as displayed on the non root account? Since the
display flag is a per account setting

**Comment by sorah** [comment]
oh thanks that was the cause! It seems hard to notice that option works on individual user basis for newly invited users.
