### ISSUE TITLE
MIX-BT displays all Swedish networks that are very much not present on MIX-BT

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#147]
URL:
```
https://bgp.tools/ixp/MIX-BT
```

Browser (User-Agent if you can): 
```
N/A
```

Error base64 blob (If a site error):
```
N/A
```

What were you expecting:
```
Networks from https://www.peeringdb.com/ix/727
```

What happened:
```
Networks from https://bgp.tools/ixp/Gavlix
```

**Comment by elinarbur** [comment]
In case this is some silly timing error, here is a screenshot as of May 19th, 2024 at 16:53
![image](https://github.com/bgptools/issues/assets/47786934/6d218d2b-9b9e-4a40-a338-ec4ea24fc165)

**Comment by benjojo** [comment]
Now that *is* an interesting bug, I can reproduce, I'll look into it

**Comment by benjojo** [comment]
EuroIX is publishing bonkers data again.

![image](https://github.com/bgptools/issues/assets/1504626/7ad853fe-f23f-421a-85bc-84b3e125d901)

I'll drop this from the imports and follow up with EuroIX at RIPE
