### ISSUE TITLE
Add a SEGA icon for IX ports showing SEGA MACs

### ISSUE THREAD

**Issue by fyx** [bgptools/issues#149]
URL:
```
https://bgp.tools/as/61229#ix
```

Browser (User-Agent if you can): 
```
N/A
```

Error base64 blob (If a site error):
```
N/A
```

What were you expecting:
```
SEGA icon for SEGA MACs on IX ports.
```

What happened:
```
The generic icon (https://bgp.tools/assets/icons/nic.png) shows up.
```
SEGA ENTERPRISES, LTD. have the OUI assignment 00:D0:F1 and I think it would be fun to have an icon added.

I've attached one that I think would work well:
<img src='https://github.com/bgptools/issues/assets/91976/75a2b6d0-4277-4b45-bc5a-bbd88ec1b482' width='24'>

**Comment by benjojo** [comment]
I decided against this, Sega (and nintendo) are particularly litigious with their brand, and I don't want to waste time with getting involved with them
