### ISSUE TITLE
Feature Request: Notice for private ASN

### ISSUE THREAD

**Issue by herbetom** [bgptools/issues#15]
I don't know how good this idea is, but i could imagine that it would be helpful to show a info box if the AS number is in a private range. 

https://www.iana.org/assignments/as-numbers/as-numbers.xhtml

The biggest problem I see with this is that it raises the question of where to stop. There is certainly more info that could be displayed, such as private IP ranges etc.

**Comment by benjojo** [comment]
_Ideally_ there is code to stop Private ASN's from being imported into the site, but clearly some are still slipping in.

I agree some effort can be done to handle the Private ASN's that do show up better

**Comment by herbetom** [comment]
> Ideally there is code to stop Private ASN's from being imported into the site, but clearly some are still slipping in.

Oh, i didn't realize that. But yes, that makes sense. I only looked at [AS64607](https://bgp.tools/as/64607). 

However, I could also imagine that it might be helpful to display a small infobox that a private ASN was queried, even for ASNs that work correctly according to the current implementation (such as [AS64608](https://bgp.tools/as/64608)).

**Comment by benjojo** [comment]
Private ASN's now at the very least get forced named `Private ASN" or `Private Documentation ASN` depending on what range they are on.

I figure that likely explains the situation well enough?

**Comment by herbetom** [comment]
Is it possible that the boundaries for this forced renaming are currently wrong by one?

https://bgp.tools/as/65536: `ERR_AS_NAME_NOT_FOUND`
https://bgp.tools/as/65537: `Private Documentation ASN`

and

https://bgp.tools/as/64512: `ERR_AS_NAME_NOT_FOUND`
https://bgp.tools/as/64513: `Private ASN`


Otherwise, yes, that does help and is probably enough. :)

**Comment by benjojo** [comment]
This should be fixed now! Sorry for the delay

**Comment by herbetom** [comment]
Yup, seems to be correct now, Thanks :)

And you don't need to appolzogize for a "delay" while fixing a absolutely minor issue in a really great tool provided for free ;)
