### ISSUE TITLE
Feature Request: LIR Services tag

### ISSUE THREAD

**Issue by anthonygarced** [bgptools/issues#151]
I believe there should be a LIR services tag (bgp.tools/tags/LIR), with the tag being blue. The explanation could be: "This network provides ASN/IP space to end users". Here's an example of what it could look like:

![P5u9pF](https://github.com/user-attachments/assets/6d4366be-334a-418c-a483-2b7dc5cda5e3)

It's also good for the rir-owner tag (for example, Zappie Host/Hyehost)

**Comment by benjojo** [comment]
LIR services is more of a sales-type thing that the company does, more than a trait of the ASN itself. So this is not a good fit for a bgp.tools tag
