### ISSUE TITLE
Bug?: Cannot setup bgp-tools-client-agent

### ISSUE THREAD

**Issue by GrapeApple0** [bgptools/issues#160]
URL:
```
https://bgp.tools/authed/approve-agent
```

Browser (User-Agent if you can): 
```
Vivaldi 6.9.3447.48 (Stable channel) (64-bit)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
But, it happened in any browser.
```

Error base64 blob (If a site error):
```
Nothing
```

What were you expecting:
```
To setup bgp-tools-client-agent
```

What happened:
```
Approval page is blank with nothing error and 200 response.(Image of page is below)
```
![screenshot 1321](https://github.com/user-attachments/assets/74837523-83c6-4d36-919b-137d0a9f58c2)

**Comment by benjojo** [comment]
This feature is only available to users who are in the agents beta, The agents will be generally available eventually
