### ISSUE TITLE
404 image is 404

### ISSUE THREAD

**Issue by km09** [bgptools/issues#19]
URL:
```
https://bgp.tools/assets/404.png
```

Browser (User-Agent if you can): 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
```

Error base64 blob (If a site error):
```
n/a
```

What were you expecting:
```
404 image 😃 
```

What happened:
```
404 but not image 😢 
```

**Comment by benjojo** [comment]
Ironic!

I think I know what caused this, give me a hour to fix this

**Comment by benjojo** [comment]
Fixed, Sorry about that!
