### ISSUE TITLE
RPKI Chain is empty for 2602:fbd0:10::/48

### ISSUE THREAD

**Issue by titanous** [bgptools/issues#20]
URL:
```
https://bgp.tools/prefix/2602:fbd0:10::/48#validation
```

Browser (User-Agent if you can): 
```
Chrome 99.0.4844.14
```

What were you expecting:
```
The ROA validation chain to be displayed. (IRR Explorer shows that it is RPKI valid: https://irrexplorer.nlnog.net/prefix/2602:fbd0:10::/48)
```

What happened:
```
The section is empty.
```

**Comment by benjojo** [comment]
Is this recently (last 10d) signed ?

**Comment by titanous** [comment]
Ah, yep. I didn't see an expected timeline for how often it's checked.

**Comment by benjojo** [comment]
The investigation to fix this has proven to me that this feature is far more broken than I thought. For the mean time, I've disabled it over the whole site. Sorry!

**Comment by benjojo** [comment]
Time sure has passed, but this feature now works again! Sorry about that
