### ISSUE TITLE
This prefix is not reachable from Hurricane Electric on IPv6, but it's reachable

### ISSUE THREAD

**Issue by HuJK** [bgptools/issues#22]
URL:
```
https://bgp.tools/prefix/2a0e:b107:1951::/48#connectivity
```

Browser (User-Agent if you can): 
```
Chrome 99
```

What happened:
```
This prefix is not reachable from Hurricane Electric on IPv6 [(What does that mean?)](https://bgp.tools/kb/partitions)
```
![image](https://user-images.githubusercontent.com/15907444/160109964-2322d0fe-c9b0-4dca-b185-8fff755f9428.png)

What were you expecting:
```
Don't show that. it is reachable from HE
```
![image](https://user-images.githubusercontent.com/15907444/160110043-d24fbdce-766b-47e1-b843-d1f3a99dbd59.png)

**Comment by benjojo** [comment]
Ah! I realise what is causing this! Give me a day and I'll fix it
