### ISSUE TITLE
Weird RPKI status

### ISSUE THREAD

**Issue by zappiehost** [bgptools/issues#25]
Hi!

We noticed a weird RPKI/IRR status, just curious to see what part is potentially misconfigured on our end OR is the information wrong? 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/102743699/176978450-fdf22788-59c9-4212-a496-2c92c36c4dc7.png">

However there is no ROA present, making this neutral (not invalid nor valid) I thought?

https://rpki.cloudflare.com/?view=validator&prefix=2a0a%3A6040%3A%3A%2F29&asn=61138&validateRoute=61138_2a0a%3A6040%3A%3A%2F29

**Comment by zappiehost** [comment]
and on that topic there is another weird case:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/102743699/176978643-74c8395a-05c9-4974-9abd-6c9b2a2c54b0.png">

Says its not valid however there is both IRR and ROA covering this:

https://rpki.cloudflare.com/?view=validator&prefix=2a0a%3A6040%3A%3A%2F29&asn=61138&validateRoute=61138_2a06%3A1280%3Ace04%3A%3A%2F48

<img width="565" alt="image" src="https://user-images.githubusercontent.com/102743699/176978660-ca9f7b07-3f12-4147-a398-4d808ff2ea31.png">

**Comment by benjojo** [comment]
Yeah I can see the issue (this is a fault in bgp.tools, not you), give me a few days to sort this out. Since there is a roadblock in place for me updating bgp.tools at the moment

**Comment by benjojo** [comment]
This issue should be fixed, sorry about that :(

There is a large overhaul on how bgp.tools deals with RPKI going on right now
