### ISSUE TITLE
Idea: "Problematic" & "Heavily problematic" ASN tags

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#27]
URL:
```
https://bgp.tools/as/208548#asinfo
```

Show tags for ASNs that often cause problems (e.g. networks used for DDoS attacks, networks advertising invalid routes, networks advertising too many routes).

Sort of a "shame" registry for bad actors.

**Comment by benjojo** [comment]
I'm pretty sure this is a large legal risk (defamation / libel) so while its nice, I'll pass :)
