### ISSUE TITLE
Wrong prefix RIR allocation

### ISSUE THREAD

**Issue by mindsolve** [bgptools/issues#30]
URL:
```
https://bgp.tools/prefix/92.215.0.0/16
```

Browser (User-Agent if you can): 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
```

Error base64 blob (If a site error):
```

```

What were you expecting:
```
The prefix to be correctly shown as assigned to RIPE
```

What happened:
```
The prefix is shown with the message `Active, Allocated under Unknown`, with the description `This network range is not allocated to APNIC`.
```

According to the IANA, the whole prefix `092/8` is allocated to RIPE. This can be verified by a RDAP query for the above mentioned prefix `92.215.0.0/16` resulting in valid data (net `DE-ARCOR-20071017`).

**Comment by benjojo** [comment]
A massive overhaul on how whois queries are sent around has landed, this issue should be fixed
