### ISSUE TITLE
Better copy-paste

### ISSUE THREAD

**Issue by ewpratten** [bgptools/issues#32]
When copying an ASN or prefx from pages like https://bgp.tools/as/204466#connectivity and https://bgp.tools/as/204466#prefixes, unless you are super careful with your mouse placement, your clipboard will pick up the text as

```text
<space><tab><actual thing you copied>
```

I would really like this space tab thing to be uncopyable, since Its pretty common for me to be copy-pasting prefixes of peers and such from the site.

**Comment by benjojo** [comment]
I don't fully understand what you mean, I also don't know what browser this happens on since you ignored my template :)

FWIW, I don't see anything in the DOM that should be causing this

![image](https://user-images.githubusercontent.com/1504626/183689117-6eb94a3e-a3db-4ea0-961b-68254b37efbb.png)

**Comment by ewpratten** [comment]
It skipped my mind this might be a browser thing.. whoops.

I encounter this on Fedora 36, Firefox 100.0.2 (64-bit)

I have attached a screenshot of my selection, and exactly what is pasted

```
 	44.31.62.0/24
```

![image](https://user-images.githubusercontent.com/21065412/183692085-3c26c1d9-b63f-40a7-888a-542536f6ccc9.png)

**Comment by ewpratten** [comment]
If I set `user-select: none;` on the `td` containing the flag and status, this issue is fixed

**Comment by benjojo** [comment]
Implemented
