### ISSUE TITLE
Pricing Page "get started" redirects to login form

### ISSUE THREAD

**Issue by craig** [bgptools/issues#33]
URL:
```
https://bgp.tools/pricing
```

Browser (User-Agent if you can): 
```
Chrome 104
```

Error base64 blob (If a site error):
```
-
```

What were you expecting:
```
Clicking on https://bgp.tools/pricing -> "get started" should show some form.
```

What happened:
```
Getting redirected to https://bgp.tools/login
```

**Comment by benjojo** [comment]
This now redirects you to billing options if you are logged in and /register if not
