### ISSUE TITLE
Feature request: Anycast tag

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#35]
I know the CDN tag already exists but I think it could be useful to add a tag for networks that announce an anycast prefix.

Not all anycast is done for CDN purposes so this would be very useful if you wanted a list of all GeoDNS providers, for example.

Let me know what you think, maybe this is a useless idea.

Kjartan

**Comment by benjojo** [comment]
I'd like to see if anyone else is interested in this, mostly because I'm not sure the tag is that useful in itself. But i'm happy to be proven wrong, since it is trivial to implement this

**Comment by mariogdn** [comment]
I would like to see the Anycast tag too, running anycast doesn't mean is a CDN.

**Comment by l27001** [comment]
I think it might be helpful for some people. +1 to add this tag

**Comment by eraters** [comment]
+1, it's true that not everyone anycasts just for CDNs

**Comment by benjojo** [comment]
Cool, will add a anycast tag then :)

**Comment by benjojo** [comment]
![image](https://user-images.githubusercontent.com/1504626/186258538-41e53de4-7b15-411f-a6ac-f08b3ef50ea3.png)

**Comment by dino801** [comment]
[]() #31
