### ISSUE TITLE
FR: Ability to Upload Organisation Photo

### ISSUE THREAD

**Issue by thatmattlove** [bgptools/issues#36]
_This is a FR, not a bug_

It'd be neat if and organisation (paid or otherwise) could customize the photo that displays on their ASN's page, rather than only using the scraped image. Scraped images don't work so well for SPAs.

If this isn't possible or desired, could you provide (or publish) the IPv4 and IPv6 address of the system that does the scraping, so users can implement some sort of workaround themselves?

Thanks!

**Comment by benjojo** [comment]
There is a issue in place (on the private issue tracker) to improve the website screenshots, however if you want to do some magic now, you can find the screenshot addresses by doing:

```
[17:26:36] ben@metropolis:~$ dig chrome-snapshots.b621.net AAAA +short
2a0c:2f07:29:666::85f1
[17:26:39] ben@metropolis:~$ dig chrome-snapshots.b621.net A +short
185.230.223.100
```

**Comment by thatmattlove** [comment]
Fantastic. Magic has been performed. Thank you!
