### ISSUE TITLE
Add code

### ISSUE THREAD

**Issue by AlphaHot** [bgptools/issues#4]
Hello, dear Ben, make the project open, please lay out all the code.

**Comment by AlphaHot** [comment]
@benjojo

**Comment by benjojo** [comment]
This is not something I'm fully prepared to do at the moment, as it's not
concrete what it would help people with, I plan to open up some of the
components of this site but the website itself is kinda too specific to the
site to be useful for anyone else, and I would also like to avoid someone
picking up the whole site 1:1 on another domain.

**Comment by benjojo** [comment]
Is there something specific about the site that you want to know how it
works?
