### ISSUE TITLE
Feature Request: Private ASNs "commonly used by"

### ISSUE THREAD

**Issue by ewpratten** [bgptools/issues#40]
A proposal. Since we can see private ASes on the website anyways, it would be cool to have a little section on their "Overview" page titled "Commonly Used By" or something of the sort.

This section could be updated with user suggestions, either via github issues, or some kind of public file we can make PRs into.

An example would be [as64515](https://bgp.tools/as/64515), which is used for peering with [Vultr](https://www.vultr.com/) customers. On this AS's page, I'd expect to see something like:

```
Commonly used by:
 - AS20473 (Peering with customers)
```

Of course, this couldn't only show one user, since private ases can be used by anyone. Maybe there are others used internally by large networks, or other hosting providers with a similar setup to vultr.

Input is appreciated.

**Comment by ewpratten** [comment]
In terms of user edit-ability, Maybe this could be added to the existing "Edit" tab for the AS?

Otherwise, maybe a JSON file could be put in this repository using some kind of easy to understand format like:

```json
{
  "AS64515": {
    "AS20473": "Peering with customers"
  }
}
```

and we could just make our edits in GIT

**Comment by benjojo** [comment]
I'm likely going to auto-strip out the vultr private hops to be honest. I figure that is better than handling vultrs weird habit of adding 2 private ASNs into the path (other than it being a great automatic anti-leak protector)

**Comment by ewpratten** [comment]
ya, fair point.

**Comment by benjojo** [comment]
Wont-Fix
