### ISSUE TITLE
Incorrect RDNS data & manual reload

### ISSUE THREAD

**Issue by ewpratten** [bgptools/issues#42]
I'm not quite sure whats up here tbh. Just check out the reverse DNS entries for this prefix.

https://bgp.tools/prefix/66.254.114.0/24#dns

![Screenshot from 2022-09-19 10-22-01](https://user-images.githubusercontent.com/21065412/191040340-cf417bd5-2098-44f4-a45e-1401047bd28e.png)

For the record, doing an actual RDNS lookup on any of these addresses returns a reasonable hostname.

```text
$ host 66.254.114.56
56.114.254.66.in-addr.arpa domain name pointer reflectededge.reflected.net.
```

**Comment by benjojo** [comment]
I've reloaded that RDNS, I know the root cause, however I'm not going to fully go into it, but it's a interaction of how they (reflected) run their RDNS servers and how my DNS stuff detects changes

**Comment by benjojo** [comment]
I'll leave this open to track the creation of a manual reload request button, just like whois has.

**Comment by benjojo** [comment]
Reload button now exists

**Comment by evnsh** [comment]
> Reload button now exists

Was the button removed at some point? Looks like the API route /internal/reload-rdns still exists but the button never show up, even on month old+ data.

**Comment by benjojo** [comment]
The current logic only allows this to show up if all are true:

(A) The DNS is already more than 1 week old
(B) There has not been a previous request to reload RDNS in the last 10 seconds
(C) IPv4 only

IPv6 zones are crawled a lot more proactively, If you think there is a larger bug that is not described here, please send it to admin@bgp.tools and I will look at it

**Comment by evnsh** [comment]
Hello! My prefix 23.169.88.0/24 matches all three conditions:
(A) Last update was in January 2024.
(B) There has not been a previous request to reload RDNS in the last 6 months
(C) Is IPv4.

Yet the button doesn't appear and old data that's been outdated since February is still being shown.

**Comment by benjojo** [comment]
I can see from my DB end that your zone has not been checked in a while:

```
id     |name                   |serialnumber|lastchanged|
-------+-----------------------+------------+-----------+
xxxxxxx|88.169.23.in-addr.arpa.|  2024020903| 1707823662|
```

The current SOA is 20240604062950, and that is today, was previous changes made before that?

I'm skipping over why the manual reload button is not showing up right now, that's a different quirk, but I'd like to double check that nothing weird has happened here
