### ISSUE TITLE
"Suggested Website is not returning a sucessful error code (403)"

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#44]
URL:
```
https://bgp.tools/edit/as/18551
```

What were you expecting:
```
I was expecting the edit to be successful.
```

What happened:
```
The website returns "Suggested Website is not returning a sucessful error code (403)".
```

This happens when attempting to add "https://www.rothschildandco.com/en/" as the website to https://bgp.tools/edit/as/18551. The website is fully functional yet it doesn't seem to play nice with bgp.tools. My thought here is that perhaps this is part of some underlying issue that could yield the same result for e.g. all websites with some sort of anti-bot protection. If not, feel free to throw this issue out :)

**Comment by benjojo** [comment]
```
$ curl https://www.rothschildandco.com/en/ -vso /dev/null |& grep HTTP
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> GET /en/ HTTP/2
< HTTP/2 403 
```

I cannot help sites that block everything non browser shaped
