### ISSUE TITLE
Cogent (AS174) showing as announcing zero IPv4 prefixes

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#48]
URL:
```
https://bgp.tools/as/174
```

What were you expecting:
```
v4 prefixes announced
```

What happened:
```
No v4 prefixes announced
```

Screenshot, for reference:

![image](https://user-images.githubusercontent.com/47786934/194891934-be1fa807-f921-4b2d-bb26-ead47682e3fc.png)

**Comment by elinarbur** [comment]
~~Looks fixed now, not sure if it was because of this ticket.~~

I spoke too soon, I'll just leave this open :)

**Comment by benjojo** [comment]
Issue noted. This is is a little involved to fix. But I'll look into fixing
this this week

**Comment by benjojo** [comment]
Issue has been partially fixed

**Comment by benjojo** [comment]
I think this issue has been solved for the most part, I will continue to monitor
