### ISSUE TITLE
Idea: IPv4 Only Tag + Dual Stack Tag?

### ISSUE THREAD

**Issue by keatonaglair** [bgptools/issues#49]
URL:
```
https://bgp.tools/as/36479
```
A bit of a "shame" tag for those networks that could dual stack but won't. Inverse of the existing IPv6 Only tag, also possibly a dual stack tag?

**Comment by benjojo** [comment]
A dual stack tag would almost encompass a huge % of all ASNs, somewhat negating the point of the tag (I prefer tags to be something notable about a network)

**Comment by keatonaglair** [comment]
So, no IPv4 Only tag?

**Comment by benjojo** [comment]
Indeed
