### ISSUE TITLE
Missing country flag for Åland Islands (AX)

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#50]
URL:
```
https://bgp.tools/prefix/2a06:1287:100::/40
```

What were you expecting:
```
I expected to see the red, yellow and blue flag of the Åland Islands on the prefix list page for AS208548.
```

What happened:
```
Instead, there is a question mark icon (https://bgp.tools/assets/flags/UNK.png). https://bgp.tools/assets/flags/AX.png does actually exist, it just does not get rendered for some reason.
```

I did some limited testing as well, by the way, on another IP block, the issue does not seem rooted in the fact that `2a06:1287:100::/40` has multiple country attributes set in RIPE.

**Comment by elinarbur** [comment]
Also, looking at https://bgp.tools/as/41878, it seems ASNs registered with the "AX" ISO country code do not receive their own "location of operation" (which would be "Åland Islands"). Thankfully the Åland Islands are a very small territory so this is not a critical issue.

**Comment by benjojo** [comment]
Fixed
