### ISSUE TITLE
Feature Request: NLNOG Looking Glass button

### ISSUE THREAD

**Issue by ewpratten** [bgptools/issues#52]
A button on the prefix pages to open the [NLNOG Looking Glass](https://lg.ring.nlnog.net/) for that prefix would be nice.

The URL format for this seems to be:

```text
https://lg.ring.nlnog.net/prefix?q=<url_encoded_prefix>&match=exact&peer=all
```

**Comment by CloudieLLC** [comment]
would be better than using ring, but to make bgp.tools exclusive one ;) since, after all, we're talking 250+ live sessions :)

**Comment by ewpratten** [comment]
In that case, I'd 100% want to see the bgp communities list and community descriptions on routes in bgp.tools

**Comment by benjojo** [comment]
Since bgp.tools has it's own looking glass now, this task is mostly done, but I've also added a NLNOG button to the bottom of the bgp.tools LG as well
