### ISSUE TITLE
Feature Request: Visual Low Visibility Button

### ISSUE THREAD

**Issue by CloudieLLC** [bgptools/issues#53]
URL:
```
https://bgp.tools/as/44570?show-low-vis#prefixes
```

Browser (User-Agent if you can): 
```
OperaGX
```

Error base64 blob (If a site error):
```
NULL
```

What were you expecting:
```
Differentiated colors between normal and low visibility routes, or a button or tag somewhere to easily scroll through and go damn, that one's dead! (only way to tell the difference is to compare between the low/high pages, and click until you find a 404 ;) memory ain't the best.
```

What happened:
```
I see dead prefixes.. 👍 
```

**Comment by benjojo** [comment]
Done, This mildly creepy grey eye will show up next to low vis prefixes, when the mode is enabled

![image](https://github.com/bgptools/issues/assets/1504626/98ff38e7-03cb-4508-a575-153d37d36791)
