### ISSUE TITLE
IX tables do not have unique HTML IDs

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#56]
URL:
```
n/a
```

Browser (User-Agent if you can): 
```
n/a
```

Error base64 blob (If a site error):
```
n/a
```

What were you expecting:
`The table element of the IX table and Virtual IX table should have unique HTML IDs (e.g. ixTable, vixTable) so they can be referenced in e.g. userscripts.`

What happened:
`The IX and Virtual IX tables both have the HTML ID "upstreamTable" which is already used on the connectivity page. As the tabs are not separate HTML documents but a clever use of JavaScript, this creates a conflict with both the real upstream table as well as the two IX tables.`

_Sidenote: This is relevant for me mostly as I've been attempting to create a userscript that shows the total peering capacity of any given network on BGP.tools._

**Comment by benjojo** [comment]
Fix for this will be deployed in the next 24 hours
