### ISSUE TITLE
IPv6 address search not yielding correct prefixes

### ISSUE THREAD

**Issue by ahrex** [bgptools/issues#57]
URL:
```
https://bgp.tools/search?q=2a03%3A6f00%3A8%3A%3A1ae6
```

Browser (User-Agent if you can): 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
```

Error base64 blob (If a site error):
```
N/A
```

What were you expecting:
```
Prefixes containing the IPv6 address 2a03:6f00:8::1ae6
```

What happened:
```
Other prefixes that don't match my query, see attached screenshot.
```

<img width="1436" alt="Screenshot 2022-11-12 at 13 45 13" src="https://user-images.githubusercontent.com/1185340/201489961-960c6752-0d95-4a0b-b170-839fe9782eb7.png">

**Comment by ahrex** [comment]
Ah nevermind, it may be because the prefix this belongs to does not exist in the global routing table.

Could I change the nature of this request to be "a clearer error message if no direct entries are found"? Maybe a blurb at the top saying "No direct hits, did you mean the following:"

**Comment by benjojo** [comment]
Just pushed this to the site:

![image](https://user-images.githubusercontent.com/1504626/210776161-60252330-7b29-4287-ad75-2917ee123a35.png)


If a realtime lookup fails, I will look back in the last 20 years of BGP tables and find when it was last seen :)

Hope this helps
