### ISSUE TITLE
signal phone registration token does not work anymore if used before (idempotency?) 

### ISSUE THREAD

**Issue by ravens** [bgptools/issues#59]
URL:
```
https://bgp.tools/authed/manage-comms?new=1
```

Browser (User-Agent if you can): 
```
Safari 16.2
```

Error base64 blob (If a site error):
```

```

What were you expecting:
```
Registration of signal method when phone has been sending the token 
```

What happened:
```
Got the error : Reason: Signal Token not valid (did you submit before you validated?)

Phone has sent the token successfully (one cross in signal) but that's it. 
Phone was upgraded from on old phone that was working with this method before. I was surprised not to receive alert, I deleted the method and could not add the method again. Phone number did not change.
```

**Comment by ravens** [comment]
ASN 211514

**Comment by benjojo** [comment]
Can you try now?

**Comment by ravens** [comment]
I just did. Same error

**Comment by benjojo** [comment]
I just tested:

A) Onboarding Signal on iPhone
B) Onboarding Signal on Android
C) Onboarding Signal on Android via Safari 16.2

All worked. Can you give more details to help me debug this? Can you try using Chrome or Firefox?

**Comment by ravens** [comment]
I switch to Chrome but no change. I just noticed this:
![image](https://user-images.githubusercontent.com/104708/207981950-66ea3d1b-b6c8-420e-af3c-b573f9d3a6cf.png)

Looks like Signal message is not received on your side, perhaps because the phone change invalidated something on signal side ? I should get double tick box, right ?

**Comment by benjojo** [comment]
Are you sure you are sending the message to the right number?

**Comment by benjojo** [comment]
Have you potentially messaged the number before and then changed your signal key (reinstalled the app)?

**Comment by ravens** [comment]
yes, indeed, as indicated in the original issue: `"Phone was upgraded from on old phone "`.

**Comment by snaakey** [comment]
This issue still persists. After changing to a new device i.e. changing the safety number I don't receive alerts anymore and it isn't possible to register with the same phone number again. AS203819

**Comment by ravens** [comment]
yes we should maybe have a way to clean out outdated signal config on the server side.

**Comment by benjojo** [comment]
This problem is now fixed, you should be able to send 1 (or 2) messages to bgp.tools and the site will accept your phone again
