### ISSUE TITLE
Documentation about what messages can be sent in the webhook

### ISSUE THREAD

**Issue by zekesonxx** [bgptools/issues#61]
**URL**:
https://bgp.tools/kb/webhook-format

**What were you expecting**:
Any details about what would be included in the alert.

**What happened**:
The KB page only describes the format of the hook (important to have!) and not any details about what will be included.
I'm assuming that it's a basic text string that matches the alerts sent via email/Discord/other methods (matching previous events listed on https://bgp.tools/authed/manage-monitoring), but some descriptive text explaining what the messages will include would be good.

For instance, some of my Discord alerts have included links, but not all of them (and no email alerts have ever had links, except for the unsubscribe link in all of them). Will the webhook requests include these? What format will they be in?

This might be better off as a wider article in itself, describing what exactly is sent to email, Discord, Slack, etc.

**Comment by benjojo** [comment]
Right now basically all notification (_except_ email) are the same on all protocols, Including webhooks.

The webhook format is actually pretty basic, and very uninteresting. A better webhook option is planned (think structured json log style) soonish. Since a larger customer is looking for it.

**Comment by benjojo** [comment]
https://bgp.tools/kb/webhook-format now has more information in it
