### ISSUE TITLE
Feature request: connectivity page: add downstreams sum and create links

### ISSUE THREAD

**Issue by ghost** [bgptools/issues#65]
Hello,

on the connectivity tab for a given ASN at the top the following infos are listed:

> Peers     1312      Upstreams      23      Cone   42

What I am missing here are "Downstreams".

And it'd be really helpful to have some HTML anchors for the categories (e. g. Downstream). Transits and Peers are usually not a problem because transits come first and are mostly just a handful. But scrolling down to the Downstreams with 1-5k peers is not very handy.  

Thanks for considering

**Comment by benjojo** [comment]
![image](https://user-images.githubusercontent.com/1504626/212566441-c55efd4a-0ad3-47d9-ae72-02407412ed4f.png)

**Comment by ghost** [comment]
awesome, thanks @benjojo
