### ISSUE TITLE
Bug: Cannot activate peerlock in "AS Relation Alerts"

### ISSUE THREAD

**Issue by ghost** [bgptools/issues#66]
URL:
```
https://bgp.tools/authed/edit-comms...
```

I try to activate peerlock in an email contact endpoint. 

I set the checkmark for "Alert on Peerlock violations" , press "save settings", the "Contact Endpoint Options" page shows again, but no checkmark in "Alert on [Peerlock violations](https://bgp.tools/kb/peerlock)"

**Comment by benjojo** [comment]
Should be fixed

**Comment by ghost** [comment]
yes, looks fixed to me. Thanks @benjojo
