### ISSUE TITLE
ERR_AS_NAME_NOT_FOUND

### ISSUE THREAD

**Issue by NickBouwhuis** [bgptools/issues#68]
URL:
```
https://bgp.tools/
```

Browser (User-Agent if you can): 
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
```

Error base64 blob (If a site error):
```

```

What were you expecting:
```
For it to say "Cambrium IT Services B.V. [AS25596]". Same as the IPv6 address.
```

What happened:
```
It shows "ERR_AS_NAME_NOT_FOUND (AS0)" instead
```

I use the site regularly and for some reason it only happens with this particular  connection. 

If I click the prefix, it says the prefix isn't in the global routing table. Seems like bgp.tools is showing a more specific to '[82.197.192.0/19](https://bgp.tools/prefix/82.197.192.0/19)'. Not sure why bgp.tools is displaying the /21 route.
 
![CleanShot 2023-02-17 at 19 10 02@2x](https://user-images.githubusercontent.com/2922075/219745176-e8baddc8-8f58-4e36-a75d-2d208390f6e1.png)

**Comment by benjojo** [comment]
This should have been fixed for at least a few months
