### ISSUE TITLE
Show "AS name" on the connectivity graphs

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#69]
URL:
```
Example: https://bgp.tools/prefix/2a07:54c3::/32#connectivity
```

Perhaps connectivity graphs could be modified to show the "AS name" of every given AS listed (https://ftp.ripe.net/ripe/asnames/asn.txt, the string immediately following the AS number separated by a space) to make it more clear which ASNs are being crossed for a route to propagate to DFZ. This could be useful as sometimes the links overlayed on top of the graph are not always in the correct place and therefore not always clickable/hoverable to reveal the name.

Here is an example of an implementation of this based on the above URL:

![](https://svgur.com/i/qTN.svg)

One drawback of this could be the inaccurate/unclear AS names that some networks will set for themselves, for example PCCW is "BTN-ASN", perhaps this could be addressed by using the existing bgptools list of network names (https://bgp.tools/asns.csv) ?

**Comment by benjojo** [comment]
Oh man, that is going to be spicy in GraphViz.

I like the idea, but I'll have to think about how to handle very long AS names

**Comment by benjojo** [comment]
![image](https://github.com/bgptools/issues/assets/1504626/8a07154a-0f07-4128-accb-fab284bcd8c2)
Done.
