### ISSUE TITLE
Extra stuff in Whois tab for ARIN ASNs.

### ISSUE THREAD

**Issue by loopyman** [bgptools/issues#70]
URL:
```
https://bgp.tools/as/13760#whois
https://bgp.tools/as/6939#whois
```

Browser (User-Agent if you can): 
```

```

Error base64 blob (If a site error):
```

```

What were you expecting:
```
Expecting what happened to not have happened.
```

What happened:
```
The Whois tab for ARIN ASNs shows extra data that seems to be meaningless to the queried ASN.
```
![image](https://user-images.githubusercontent.com/23000658/220197849-2df10adf-dbf6-456c-8779-fd4edde96912.png)

**Comment by benjojo** [comment]
Fix is out in staging, should be cleared up in the next 3 days
