### ISSUE TITLE
Show country code when querying an ASN or IPs

### ISSUE THREAD

**Issue by eraters** [bgptools/issues#71]
When you use the whois server hosted on BGP.tools to lookup an ASN or IPs, it does not return the country code.
![image](https://user-images.githubusercontent.com/54771596/221177206-473f2a66-3ef8-40ea-9f79-645f473f286f.jpeg)
![image](https://user-images.githubusercontent.com/54771596/221177229-8a2be08d-3cc4-4cd9-939a-9d9004d1bb56.jpeg)

**Comment by benjojo** [comment]
This problem is known, And only impacts RIPE prefixes/ASNs for now
