### ISSUE TITLE
Communications endpoint doesn't allow email in subdomain

### ISSUE THREAD

**Issue by caguiclajmg** [bgptools/issues#72]
URL:
```
https://bgp.tools/authed/manage-comms?new=1
```

Browser (User-Agent if you can): 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
```

Error base64 blob (If a site error):
```
None
```

What were you expecting:
```
Email (test@subdomain.example.com) will be added as a communication method
```

What happened:
```
Error appears: "Reason: invalid Email Address"
```

The pattern used for email address validation doesn't seem to expect a subdomain in the domain part.

**Comment by benjojo** [comment]
Can you please email the email address in question to ***@***.*** ?
Since this should work

**Comment by caguiclajmg** [comment]
Looks like it checks if there's an MX record for the domain, apparently I didn't push the additional records to my authoritative nameservers.
