### ISSUE TITLE
Make searching by IP like bgp.he.net

### ISSUE THREAD

**Issue by bottiger1** [bgptools/issues#75]
Another thing I am missing after switching from bgp.he.net is when you search for an ip it doesn't automatically go to the page for the prefix.

By having a page for the specific IP you can show things like RDNS for that specific ip instead of having a giant list for every ip in the prefix or a table of DNSBL. 

For those of you who care only about the BGP side, it'll also be interesting to see if the ip is being announced with different prefix sizes like this.

![image](https://user-images.githubusercontent.com/55270538/229870948-91724280-5c70-4ccc-9e79-dbd886bfeb9f.png)

![image](https://user-images.githubusercontent.com/55270538/229871386-535304e7-4ade-42f8-bbaf-9590ccb432fc.png)

**Comment by benjojo** [comment]
If you use the search function, the site will redirect you to the most specific prefix, the page itself will also have a list of less specific prefixes as well!

I don't wish to implement RBL like he.net does, as it will be more pain than I'm willing to deal with for maintenance
