### ISSUE TITLE
Some ASNs show incorrect EU flag instead of national one

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#78]
URL:
```
https://bgp.tools/rankings/IS
```

Look for AS30818 it is a good example.

**Comment by elinarbur** [comment]
![image](https://user-images.githubusercontent.com/47786934/235386608-589cfa59-f1e4-4af9-94ea-92a33fcfc937.png)

Image shows the borked flags vs. the normal ones. This happens for more ASNs but not across all of them and seemingly at random.

**Comment by benjojo** [comment]
This will clear in the next 24 hours, RIPE appears to have published a
delegate file with no ASNs in it... It's now been fixed. But caches need to
expire

**Comment by benjojo** [comment]
Issue should be fixed
