### ISSUE TITLE
Rankings intermittently 404ing

### ISSUE THREAD

**Issue by FHRNet** [bgptools/issues#80]
URL:
```
https://bgp.tools/rankings/NZ?sort=eyeballs
```

Browser (User-Agent if you can): 
```

```

Error base64 blob (If a site error):
```

```

What were you expecting:
```
Page shows rankings
```

What happened:
```
The /rankings/<country> endpoint seems to periodically return 404 instead of the ranking tables.

> The thing you are looking for likely doesnt exist.
> Sorry! Check your query for errors

This seems unrelated to the actual country being queried, trying a few at the moment (US,NZ,CZ) the end result is the same - 404.
```

**Comment by benjojo** [comment]
To clarify, is this solved by reloading the page? or are rankings just not present at times?

**Comment by FHRNet** [comment]
This seems to be randomly happening, I tried again approximately 3 hours after reporting this and the rankings were there. It does not seem to be resolved by simply reloading the page. I can try to record some timestamps next time, however you can probably see the 404s in access logs.

**Comment by benjojo** [comment]
I found the cause to be a TTL being too short, I've bumped it up and deployed the change, should fully take impact in ~12 hours
