### ISSUE TITLE
Port Speed data is not imported from IX-F feeds

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#83]
URL:
```
https://bgp.tools/as/209933#ix
```

Browser (User-Agent if you can): 
```
N/A
```

Error base64 blob (If a site error):
```
N/A
```

What were you expecting:
```
The LOCIX Frankfurt port should display a speed of 1Gbps as according to the same network's PeeringDB entry. Note that the PeeringDB entry had not been updated recently (last 27 Feb.) so this is not a case of waiting for re-import.
```

What happened:
```
A speed of "N/A" is displayed, behaviour similar to networks who exclude the particular port from their PeeringDB entry and IX-F is imported instead. (Or perhaps it wasn't IX-F but something else, I recall it being IX-F though).
```

**Comment by benjojo** [comment]
Notes:

```
$ curl -s https://manager.locix.online/api/v4/member-export/ixf/0.7 | jq . | grep -B 2 -A 20 'asnum": 209933,'
    },
    {
      "asnum": 209933,
      "member_since": "2023-01-02T00:00:00Z",
      "url": null,
      "name": "David Andri Jakobsson",
      "peering_policy": "open",
      "member_type": "peering",
      "connection_list": [
        {
          "ixp_id": 1,
          "state": "active",
          "if_list": [
            {
              "switch_id": 16,
              "if_speed": 1000
            }
          ],
          "vlan_list": [
            {
              "vlan_id": 2,
              "ipv4": {
                "address": "185.1.167.103",
```

**Comment by benjojo** [comment]
table data:

|id|asn|ipaddr4|ipaddr6|speed|peeringdb_ix_id|switchinfo|vlanname|
|--|---|-------|-------|-----|---------------|----------|--------|
|13913|209933|185.1.167.103|2001:7f8:f2:e1::20:9933:1|0|2084|xTom FRA2 (firstcolo/Accelerated) - Accelerated IT Services [Germany]|default|

**Comment by benjojo** [comment]
Ah, it's a bodge, no port speed data is currently imported from IX-F (unless it's LINX) due to weird issues that I could not nail down, I'll leave this open to track it later on

**Comment by benjojo** [comment]
The original case is that their PeeringDB entry does not have their v4 address, so something on my end is not matching the IX-F data together correctly by using the v6 addresses.

Given that serious IPv6 only IXPs are quite rare, that will fixed another time

**Comment by benjojo** [comment]
There is now a heuristic, if more than 40% of the IX-F feed port speeds match with PeeringDB, then the IX-F speed data is imported, otherwise, it will defer to PeeringDB
