### ISSUE TITLE
RPKI icon on DNS lookup page could be confused for ASPA

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#86]
URL:
```
E.g. https://bgp.tools/dns/github.com
```

Current layout (see below) implies that the ASN (AS36459 in this case) has valid ASPA.

Visitors that have been to the site before and spotted an ASPA-valid ASN in the connectivity tab will not intuitively realise this icon has to do with the prefix's RPKI status without hovering over it to view the title.

![image](https://github.com/bgptools/issues/assets/47786934/f49ec51c-e453-4ac6-abef-06f162c412fa)

_A_ solution to this could be the following, at least it feels like the most logical and obvious solution:

![image](https://github.com/bgptools/issues/assets/47786934/fb91649a-e0b5-4d7b-99d8-8ae834301a34)

**Comment by benjojo** [comment]
but ASPA only applies to upstreams and downstreams, What would the green
lock imply in ASPA terms in the first image?

(Also if you hover over the lock it describes what it is)
