### ISSUE TITLE
Feature Request: Add ranking for amount of address space originated

### ISSUE THREAD

**Issue by asdfjkluiop** [bgptools/issues#90]
One of my favorite stats from the HE BGP toolkit is the ranking by number of IPv4 addresses originated however for IPv6 HE only provides a ranking based on number of prefixes which is not the same thing. I would love a ranking for amount of address space originated. For IPv4 number of addresses(like HE) or number of /24s could be used and for IPv6 number of /48s could be used.

**Comment by benjojo** [comment]
Done
![image](https://github.com/bgptools/issues/assets/1504626/00dcb807-e190-444a-a50a-7920ab7f9c61)
