### ISSUE TITLE
Sorting feature sometimes didn't working

### ISSUE THREAD

**Issue by rapdodge** [bgptools/issues#93]
URL:
```
Sample page that sorting feature that working
https://bgp.tools/as/24482#ix
https://bgp.tools/as/15133#ix

Sample page that sorting feature that doesn't working
https://bgp.tools/as/54113#ix
https://bgp.tools/as/63293#ix
```

Browser (User-Agent if you can): 
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188
```

Error base64 blob (If a site error):
```

```

What were you expecting:
```
Sorting feature available to all networks.
```

What happened:
```
The sorting feature didn't work to some networks.
```

https://github.com/bgptools/issues/assets/33513626/aa6121a0-62be-4dcb-8b39-b70e4d83cce9

**Comment by benjojo** [comment]
Should be fixed, thanks for the report

**Comment by rapdodge** [comment]
Dear @benjojo,

I'm just wanted to let you know, that right now, I'm testing AS6939 has same issues, can't sort.

Would you mind checking it?

Best regards,

https://github.com/bgptools/issues/assets/33513626/c5bd9964-2d8b-4870-b3a0-b2d7818a3d15

**Comment by benjojo** [comment]
Should be fixed again, sorry about that
