### ISSUE TITLE
Rankings section does not display consistently between ASNs

### ISSUE THREAD

**Issue by elinarbur** [bgptools/issues#94]
URL:
```
https://bgp.tools/as/51019#asinfo vs https://bgp.tools/as/57851#asinfo
```

Browser (User-Agent if you can): 
```
N/A
```

Error base64 blob (If a site error):
```
N/A
```

What were you expecting:
```
I expect to see AS51019 shown as #1 in Iceland, similar to the section on AS57851.
```

What happened:
```
It does not.
```

**Comment by benjojo** [comment]
I am obviously very late to the party here, but I'm not sure I get what this bug was, so I will close it for now, let me know if you remember what this was and can explain better :)

**Comment by elinarbur** [comment]
(Replying here to add context, ~~hoping I can close the issue myself after commenting~~ OK awesome it just stays close).

Basically the ASN rankings section did not always display on the ASN's page, being replaced by the old "Locations of operations" section, but now it seems to display consistently. Image for reference:
![image](https://github.com/user-attachments/assets/e142c310-2721-4d7e-9388-f0ce8a3354f9)
