### ISSUE TITLE
JPIRR data is not reflected.

### ISSUE THREAD

**Issue by ghost** [bgptools/issues#95]
URL:
This prefix in IIJ is shown as an example.
https://bgp.tools/prefix/49.239.64.0/18

What were you expecting:
I would like to see the JPIRR route object reflected appropriately.

What happened:

I am not sure if this is a temporary problem, but as shown in the URL above, the JPIRR route object that should be displayed is not displayed. (From memory, I think it used to reflect correctly.)

```
# whois 49.239.64.0/18 -h jpirr.nic.ad.jp
route: 49.239.64.0/18
descr: IIJ IPv4 BLOCK ( AS2497 )
origin: AS2497
mnt-by: MAINT-AS2497
changed: shuhei-o@iij.ad.jp 20230622
source: JPIRR
```

**Comment by benjojo** [comment]
~bgp.tools has never displayed JPIRR due to the inability to mirror the IRR repo.~

bgp.tools cannot mirror the JPIRR repo, meaning that it cannot display it. The site used to outsource the database pulling from another system that could mirror JPIRR and so displayed data there. But since the site is now doing it's own mirroring, I cannot display JPIRR

If you happen to know anyone who runs JPIRR, I would love to talk to them about being able to mirror the database.

**Comment by ghost** [comment]
I seem to have misremembered about the support....

At least irrexplorer and others that bgp.tools provides data for should be mirroring and getting JPIRR data with IRRD v4.
~~although the update frequency is semi-monthly.~~
I don't know what source bgp.tools gets its data from, but you might want to rely on irrexplorer's for at least some of it.

The fact that the JPIRR AS-SET and route objects are not displayed is quite critical for Japanese users.
I know this is a busy time for you and I hope you can resolve this issue.

**Comment by benjojo** [comment]
JPIRR's server (`jpirr.nic.ad.jp:43`) refuses all IRR mirroring attempts, I was not about to find a workaround for this.

I just get back: 

> `% ERROR: mirror access denied`

This is fatal, as bgp.tools needs to NRTM IRR to work correctly, If you happen to know who to contact about this I would love to speak to them, but I could not find people to contact about this

**Comment by ghost** [comment]
Does it reject mirrors by default? I'm not familiar with it in that direction, so I don't know.
Hmmm...for reference, you have the following information.
https://www.nic.ad.jp/doc/jpnic-01263.html
In addition, the following statement was made as the contact person for inquiries.
```
Q.8-20 | JPIRRに関する問い合わせ先を教えてください。
A.8-20 | JPIRRに関する質問は irr-query@nic.ad.jp までお送りください。
```
Why don't you contact them once?

**Comment by benjojo** [comment]
JPIRR is now being mirrored, I found a workaround to their strict
mirroring policy.
