### ISSUE TITLE
Told to enable multihop when peering over IX

### ISSUE THREAD

**Issue by quantum5** [bgptools/issues#97]
URL:
```
https://bgp.tools/authed/manage-peering?new=2
```

This is the screen shown after creating a BGP session. In my case, this was over an IXP.

What were you expecting:
```
Please peer with our IP: [redacted IXP IP] on AS212232

With your IP: [redacted IXP IP] on AS[redacted]

Send a full table (as if you were sending to a customer).
```

What happened:
```
Please peer with our IP: [redacted IXP IP] on AS212232

With you IP: [redacted IXP IP] on AS[redacted]

Send a full table (as if you were sending to a customer), and don't forget to enable multihop!
```

I don't think the multihop reminder is helpful for IXP peering when I am on the same LAN as the route collector. It's probably better to have multihop off here.

Site note: it also says "with you [sic] IP" instead of "with your IP".

**Comment by benjojo** [comment]
Nice catch! I didnt consider to change the message for IX sessions but I'll mirror this issue into my private tracker!
