### ISSUE TITLE
Feature Request: Adding rank for "Prefixes Originated"

### ISSUE THREAD

**Issue by rapdodge** [bgptools/issues#98]
URL:
```
Non applicable
```

Browser (User-Agent if you can): 
```
Non applicable
```

Error base64 blob (If a site error):
```
Non applicable
```

What were you expecting:

There is rank for 'Prefixes Originated" on both v4 v6 like "Originated IPv4/IPv6 Space in (Country)"

What happened:

I felt that the ranking should be there, because I noticed that some networks were deaggregating their IP space, and, their networks had no significant impact on my network. In short, I want to save RAM on my BGP router, and I feel that the ranking list should be there to make it easier for me.

**Comment by benjojo** [comment]
I have considered this, but I will not do it as it will likely encourage people to announce more prefixes, something the DFZ does not need.

**Comment by rapdodge** [comment]
> I have considered this, but I will not do it as it will likely encourage people to announce more prefixes, something the DFZ does not need.

What if making it as "Wall of Shame"?

Because I've had enough for a network that is not essential for me but deaggregate sooo much prefixes with example this:

https://bgp.tools/as/38496

Or maybe making it somewhat unlisted, or making it available on JSON API only

**Comment by benjojo** [comment]
bgp.tools tries to avoid APIs, since it is ultimately a website for humans, not bots.

You can query your own table for top N ASNs with originating prefixes by doing something like:

```
birdc s ro | pcregrep -o1 ".AS(\d+).*$" | sort |uniq -c | sort -n
```

Or using the bgp.tools table itself:

```
$ cat Downloads/table-28-08-23.jsonl | jq .ASN | sort | uniq -c | sort -n
```

**Comment by rapdodge** [comment]
> bgp.tools tries to avoid APIs, since it is ultimately a website for humans, not bots.
> 
> You can query your own table for top N ASNs with originating prefixes by doing something like:
> 
> ```
> birdc s ro | pcregrep -o1 ".AS(\d+).*$" | sort |uniq -c | sort -n
> ```
> 
> Or using the bgp.tools table itself:
> 
> ```
> $ cat Downloads/table-28-08-23.jsonl | jq .ASN | sort | uniq -c | sort -n
> ```

Thank you for the advice!

Will use the BIRD2 command :)
